name: E2E Tests with Playwright

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run E2E tests nightly at 3 AM UTC
    - cron: '0 3 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio playwright
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        playwright install-deps
    
    - name: Run E2E Tests
      env:
        # Test environment variables
        BASE_URL: "https://arccorp-web.redlegion.org"
        HEADLESS: "true"
        SLOWMO: "0"
        TIMEOUT: "30000"
      run: |
        python -m pytest tests/test_e2e_playwright.py -v --tb=short --maxfail=5
    
    - name: Generate E2E Test Report
      if: always()
      run: |
        python -m pytest tests/test_e2e_playwright.py --junitxml=e2e-test-report.xml
    
    - name: Upload E2E Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-results
        path: e2e-test-report.xml
    
    - name: Upload Screenshots on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots
        path: test-results/