name: Infrastructure Health Check

on:
  workflow_dispatch:
  schedule:
    # Run every 6 hours to catch infrastructure issues early
    - cron: '0 */6 * * *'
  pull_request:
    branches: [ main ]

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install asyncpg httpx pytest pytest-asyncio
    
    - name: Run Infrastructure Health Checks
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
        BOT_API_URL: ${{ vars.BOT_API_URL || 'http://10.128.0.2:8001' }}
      run: python tests/infrastructure_health_check.py