name: Unit Tests

on:
  pull_request:
    branches: [ main, ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov httpx asyncpg PyJWT
        pip install -r requirements.txt
    
    - name: Run Authentication Tests
      run: |
        python -m pytest tests/test_authentication.py -v --cov=. --cov-report=term-missing
    
    - name: Run Database Tests
      run: |
        python -m pytest tests/test_database.py -v --cov=. --cov-report=term-missing
    
    - name: Generate Coverage Report
      run: |
        python -m pytest tests/ --cov=. --cov-report=xml --cov-report=html
    
    - name: Upload Coverage to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/